### ISSUE TITLE
Resume Article content, HTML encoding in list of articles

### ISSUE THREAD

**Issue by MathieuDelmarre** [odiseoteam/SyliusBlogPlugin#10]
The HTML encoding for article.content in list of articles is not good.

I have this when I use accents in my content of article  :
![image](https://user-images.githubusercontent.com/60355887/78972657-8b986380-7b0e-11ea-9972-7b3879ec17c1.png)

So to fix this we need to change in OdiseoSyliusBlogPlugin/views/Shop/Article/index.html.twig

**REMOVE :**
```twig
<p>{{ article.content|striptags|length > 200 ? article.content|striptags|slice(0, 200) ~ '...' : article.content|striptags }}</p>
```
**ADD :** 
```twig
<p>
{% if article.content|striptags|length > 200 %}
 {{ article.content|striptags|slice(0, 200)|raw }}...
{% else %}
 {{ article.content|raw }}
{% endif %}
</p>
```

**The result is :** 
![image](https://user-images.githubusercontent.com/60355887/78973325-f5fdd380-7b0f-11ea-8b30-7bae191b8ae4.png)

**Comment by bigboss86** [comment]
Hi @MathieuDelmarre. Thanks for your contribution. We have released a new version that solves this problem.
Regards!
