### ISSUE TITLE
Removing comment also removes article associated with it

### ISSUE THREAD

**Issue by zlotte** [odiseoteam/SyliusBlogPlugin#11]
While exploring plugin I've found bug that when I remove the comment from article then the article itself is also being removed. 

I've found out that it's because of this yml code block:

     manyToOne:
        article:
            targetEntity: Odiseo\BlogBundle\Model\ArticleInterface
            inversedBy: comments
            cascade: [ALL]
            joinColumn:
                name: article_id
                referencedColumnName: id
                onDelete: CASCADE

The bug caused by this cascade: `cascade: [ALL]` and if it's changed to `cascade: [persist]` then everything works fine. 

This is the file and the line
vendor/odiseoteam/blog-bundle/src/Resources/config/doctrine/model/ArticleComment.orm.yml:38

**Comment by bigboss86** [comment]
Hi @zlotte, it's already fixed.
Thanks for the contribution.
