### ISSUE TITLE
Return value of Odiseo\BlogBundle\Model\Article::getImages() must implement interface Doctrine\Common\Collections\Collection, null returned

### ISSUE THREAD

**Issue by gamusta** [odiseoteam/SyliusBlogPlugin#12]
**Sylius version** : 1.7.0

After creating a blog article and go to the listing (/admin/blog/articles/) I got this error
`Return value of Odiseo\BlogBundle\Model\Article::getImages() must implement interface Doctrine\Common\Collections\Collection, null returned`

Tested with an existed Sylius installation and a new one the same error occurs.

**Screenshot**
![image](https://user-images.githubusercontent.com/8771520/88240372-d2096c80-cc7e-11ea-85a4-ca45270e6f94.png)

**Comment by bigboss86** [comment]
Hello @gamusta. I tested it with Sylius 1.7 version and it works fine. Maybe it's something from your local settings?
