### ISSUE TITLE
Template reference "SyliusUiBundle:Macro:messages.html.twig" not found

### ISSUE THREAD

**Issue by mdhgriffiths** [odiseoteam/SyliusBlogPlugin#16]
I was having this issue with installation of `odiseoteam/sylius-blog-plugin@v1.2`  and visiting `/blog/articles` route:

```
Template reference "SyliusUiBundle:Macro:messages.html.twig" not found, did you mean "@SyliusUi/Macro/messages.html.twig" in @OdiseoSyliusBlogPlugin/Shop/Article/index.html.twig at line 3
```

It appears to work be updating the template reference as recommended in [src/Resources/views/Shop/Article/index.html.twig](https://github.com/odiseoteam/SyliusBlogPlugin/blob/master/src/Resources/views/Shop/Article/index.html.twig#L2).

```diff
- {% import 'SyliusUiBundle:Macro:messages.html.twig' as messages %}
+ {% import '@SyliusUi/Macro/messages.html.twig' as messages %}
```

**Comment by bigboss86** [comment]
Solved! Thanks @mdhgriffiths
