### ISSUE TITLE
Unable to install the Plugin on Sylius 1.9.2 and Sylius 1.8.5

### ISSUE THREAD

**Issue by Basti271** [odiseoteam/SyliusBlogPlugin#17]
Hi, 
I was trying to get the Plugin running on Sylius 1.9.2 and also Sylius 1.8.5 but without success.

I do get the following errors:

> Problem 1
    - odiseoteam/sylius-blog-plugin[v1.2.0, ..., v1.2.2] require odiseoteam/blog-bundle ^1.1 -> satisfiable by odiseoteam/blog-bundle[v1.1.0, ..., v1.1.23].
    - odiseoteam/blog-bundle[v1.1.0, ..., v1.1.6] require symfony/framework-bundle ^3.4|^4.1 -> found symfony/framework-bundle[v3.4.0, ..., v3.4.47, v4.1.0, ..., v4.4.22] but the package is fixed to v5.2.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - odiseoteam/blog-bundle[v1.1.7, ..., v1.1.23] require monolog/monolog ~1.22 -> found monolog/monolog[1.22.0, ..., 1.26.0] but the package is fixed to 2.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires odiseoteam/sylius-blog-plugin ^1.2 -> satisfiable by odiseoteam/sylius-blog-plugin[v1.2.0, v1.2.1, v1.2.2]. 
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

I tried to run the installation "--with-all-dependencies" but this totally broke my vendor.

Any help would be great!

Kind regards

**Comment by bigboss86** [comment]
Hi @Basti271. Are you trying to install it on a clean sylius?

**Comment by Basti271** [comment]
Hi @bigboss86,

yes, I just tried with a complete new installation and got the same errors.

**Comment by venomsnake92** [comment]
Hi, same error here. 
Howewer, i managed to complete the installation downgrading monolog/monolog to version 1.26.0.

**Comment by Basti271** [comment]
Hi @venomsnake92,
thanks, downgrading also helped in my case. But I do have another issue now: https://github.com/odiseoteam/SyliusBlogPlugin/issues/18

**Comment by bigboss86** [comment]
Hi guys! I have updated the plugin to remove the required monolog dependencies
Thanks!
