### ISSUE TITLE
non-existent parameter

### ISSUE THREAD

**Issue by Dekminoz** [odiseoteam/SyliusBlogPlugin#2]
Hello,

i've follow all the docs but i've an error :  

You have requested a non-existent parameter "odiseo_blog.model.article.class". 

My _sylius.yaml:

> imports:
> - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
> - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
> - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
> - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
> - { resource: "@OdiseoSyliusBlogPlugin/Resources/config/config.yml" }
> - { resource: "@BitBagSyliusCmsPlugin/Resources/config/config.yml" }
                                                 
My bundles.php:

> <?php
> 
> return [
>     Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
>     Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
>     Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
>     Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
>     Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
>     Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
>     Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
>     Sylius\Bundle\OrderBundle\SyliusOrderBundle::class => ['all' => true],
>     Sylius\Bundle\MoneyBundle\SyliusMoneyBundle::class => ['all' => true],
>     Sylius\Bundle\CurrencyBundle\SyliusCurrencyBundle::class => ['all' => true],
>     Sylius\Bundle\LocaleBundle\SyliusLocaleBundle::class => ['all' => true],
>     Sylius\Bundle\ProductBundle\SyliusProductBundle::class => ['all' => true],
>     Sylius\Bundle\ChannelBundle\SyliusChannelBundle::class => ['all' => true],
>     Sylius\Bundle\AttributeBundle\SyliusAttributeBundle::class => ['all' => true],
>     Sylius\Bundle\TaxationBundle\SyliusTaxationBundle::class => ['all' => true],
>     Sylius\Bundle\ShippingBundle\SyliusShippingBundle::class => ['all' => true],
>     Sylius\Bundle\PaymentBundle\SyliusPaymentBundle::class => ['all' => true],
>     Sylius\Bundle\MailerBundle\SyliusMailerBundle::class => ['all' => true],
>     Sylius\Bundle\PromotionBundle\SyliusPromotionBundle::class => ['all' => true],
>     Sylius\Bundle\AddressingBundle\SyliusAddressingBundle::class => ['all' => true],
>     Sylius\Bundle\InventoryBundle\SyliusInventoryBundle::class => ['all' => true],
>     Sylius\Bundle\TaxonomyBundle\SyliusTaxonomyBundle::class => ['all' => true],
>     Sylius\Bundle\UserBundle\SyliusUserBundle::class => ['all' => true],
>     Sylius\Bundle\CustomerBundle\SyliusCustomerBundle::class => ['all' => true],
>     Sylius\Bundle\UiBundle\SyliusUiBundle::class => ['all' => true],
>     Sylius\Bundle\ReviewBundle\SyliusReviewBundle::class => ['all' => true],
>     Sylius\Bundle\CoreBundle\SyliusCoreBundle::class => ['all' => true],
>     Sylius\Bundle\ResourceBundle\SyliusResourceBundle::class => ['all' => true],
>     Sylius\Bundle\GridBundle\SyliusGridBundle::class => ['all' => true],
>     winzou\Bundle\StateMachineBundle\winzouStateMachineBundle::class => ['all' => true],
>     Sonata\CoreBundle\SonataCoreBundle::class => ['all' => true],
>     Sonata\BlockBundle\SonataBlockBundle::class => ['all' => true],
>     Sonata\IntlBundle\SonataIntlBundle::class => ['all' => true],
>     Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle::class => ['all' => true],
>     JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
>     FOS\RestBundle\FOSRestBundle::class => ['all' => true],
>     Knp\Bundle\GaufretteBundle\KnpGaufretteBundle::class => ['all' => true],
>     Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
>     Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
>     Payum\Bundle\PayumBundle\PayumBundle::class => ['all' => true],
>     Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
>     WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle::class => ['all' => true],
>     Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
>     Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['all' => true],
>     Sylius\Bundle\FixturesBundle\SyliusFixturesBundle::class => ['all' => true],
>     Sylius\Bundle\PayumBundle\SyliusPayumBundle::class => ['all' => true],
>     Sylius\Bundle\ThemeBundle\SyliusThemeBundle::class => ['all' => true],
>     Sylius\Bundle\AdminBundle\SyliusAdminBundle::class => ['all' => true],
>     Sylius\Bundle\ShopBundle\SyliusShopBundle::class => ['all' => true],
>     FOS\OAuthServerBundle\FOSOAuthServerBundle::class => ['all' => true],
>     Sylius\Bundle\AdminApiBundle\SyliusAdminApiBundle::class => ['all' => true],
>     Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true, 'test_cached' => true],
>     Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true, 'test_cached' => true],
>     Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true, 'test' => true, 'test_cached' => true],
>     Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true, 'test' => true, 'test_cached' => true],
>     Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true, 'test_cached' => true],
>     FriendsOfBehat\SymfonyExtension\Bundle\FriendsOfBehatSymfonyExtensionBundle::class => ['test' => true, 'test_cached' => true],
>     Sylius\Behat\Application\SyliusTestPlugin\SyliusTestPlugin::class => ['test' => true, 'test_cached' => true],
>     Odiseo\BlogBundle\OdiseoBlogBundle::class => ['all' => true],
>     FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true],
>     SitemapPlugin\SitemapPlugin::class => ['all' => true],
>     BitBag\SyliusCmsPlugin\BitBagSyliusCmsPlugin::class => ['all' => true],
>     Odiseo\SyliusBlogPlugin\OdiseoSyliusBlogPlugin::class => ['all' => true],
> ];
> 
Sylius Version : 1.4

Thx for any help.

**Comment by songecko** [comment]
Hi @Dekminoz , you need put the OdiseoBlogPlugin class before SyliusResourceBundle, like this:

...
Odiseo\SyliusBlogPlugin\OdiseoSyliusBlogPlugin::class => ['all' => true], ];
Sylius\Bundle\ResourceBundle\SyliusResourceBundle::class => ['all' => true], 
...

**Comment by Dekminoz** [comment]
It's work , Thx for your help !
