### ISSUE TITLE
Can you fix Fatal error: Type of $mappingFormat must be string?

### ISSUE THREAD

**Issue by amanis513** [odiseoteam/SyliusBlogPlugin#22]
Hello,

can you fix Fatal error: Type of Odiseo\BlogBundle\OdiseoBlogBundle::$mappingFormat must be string  (as in class Sylius\Bundle\ResourceBundle\AbstractResourceBundle) in C:\xampp\htdocs\sudekusa-shop\vendor\odiseoteam\blog-bundle\src\OdiseoBlog Bundle.php on line 35

Problem is on php 8.0.19
sylius\sylius: 1.11.13

...
final class OdiseoBlogBundle extends AbstractResourceBundle
{
    protected $mappingFormat = ResourceBundleInterface::MAPPING_YAML;
to
    protected string $mappingFormat = ResourceBundleInterface::MAPPING_YAML;
...

Thank you

**Comment by bigboss86** [comment]
Hello,
Feel free to contribute if you have time. This plugin will be free forever.
Thanks!

**Comment by amanis513** [comment]
closed

**Comment by roromix** [comment]
I have send a PR here: https://github.com/odiseoteam/OdiseoBlogBundle/pull/14

**Comment by bigboss86** [comment]
Merged! Thank you @roromix
