### ISSUE TITLE
Composer installer

### ISSUE THREAD

**Issue by skony20** [odiseoteam/SyliusBlogPlugin#26]
Hello 
I have error when I try instal by composer 

The service "odiseo_sylius_blog_plugin.factory.article_comment" has a dependency on a non-existent service "odiseo_blog.factory.article_comment".

Any idea how to fix this ?

**Comment by Tsolmonx** [comment]
i have same problem in sylius 1.12
 
In ParameterBag.php line 93:
You have requested a non-existent parameter "odiseo_blog.model.article.class".

**Comment by Tsolmonx** [comment]
https://github.com/odiseoteam/SyliusBlogPlugin/issues/2 this one helped me

**Comment by skony20** [comment]
Thanks a lot, it works
