### ISSUE TITLE
Typo in templates

### ISSUE THREAD

**Issue by matthiez** [odiseoteam/SyliusBlogPlugin#4]
There are 2 minor typos in 2 templates:

views/Shop/Article/_comment.html.twig line 25:
`'redurectParameters': {'slug': comment.article.slug }`
should be:
`'redirectParameters': {'slug': comment.article.slug }`

and

views/Shop/Article/show.html.twig line 65:
`'redurectParameters': {'slug': article.slug }`
should be:
`'redirectParameters': {'slug': article.slug }`

I will make a pull request over the weekend.
Cheers!

**Comment by songecko** [comment]
Thanks @matthiez for your contribution!

**Comment by songecko** [comment]
Thanks again @matthiez !
